name: Lint Code  
  
on:  
  push:  
    branches:  
      - main  
  
jobs:  
  lint:  
    name: Lint  
    runs-on: ubuntu-latest  
    steps:  
      - name: Check out repository  
        uses: actions/checkout@v2  
  
      - name: Set up Python  
        uses: actions/setup-python@v2  
        with:  
          python-version: 3.x
  
      - name: Install dependencies  
        run: |  
          python -m pip install --upgrade pip  
          pip install black flake8  
   
      - name: Format with black  
        run: black .
  
      - name: Lint with flake8  
        run: flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics  
        continue-on-error: false